SELECT *
FROM COUNTRIES;

UPDATE COUNTRIES
SET COUNTRY_NAME='호주',REGION_ID=2
WHERE COUNTRY_ID='AU';

SELECT *
FROM REGIONS;

DELETE REGIONS
WHERE REGION_ID=7;
ROLLBACK;

DELETE TREGIONS
WHERE REGION_ID>4;

--사번이 110번 사원의 부서명 조회
SELECT * 
FROM EMPLOYEES;

SELECT DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID=110;

SELECT DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE DEPARTMENT_ID=
        (SELECT DEPARTMENT_ID
        FROM EMPLOYEES
        WHERE EMPLOYEE_ID=110)
;
--------Sub Query----------
--사원의 모든 정보를 조회,평균 급여보다 많이 받는 사원들--
SELECT *
FROM EMPLOYEES
WHERE SALARY>
    (SELECT AVG(SALARY)
    FROM EMPLOYEES);

SELECT AVG(SALARY)
FROM EMPLOYEES;

--사번이 198인 사원이 근무하는 부서의 도시명 (LOCATION)
SELECT * FROM LOCATIONS;



SELECT * FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS;

SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 198;
SELECT LOCATION_ID FROM DEPARTMENTS WHERE DEPARTMENT_ID = 50;
SELECT CITY FROM LOCATIONS WHERE LOCATION_ID = 
        (SELECT LOCATION_ID FROM DEPARTMENTS WHERE DEPARTMENT_ID = 
            (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 198));
            
--사원번호가 199번인 사원의 매니저가 근무하는 부서가 있는 나라?
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT * FROM LOCATIONS;
SELECT * FROM COUNTRIES;
SELECT MANAGER_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 199;
SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 124;
SELECT LOCATION_ID FROM DEPARTMENTS WHERE DEPARTMENT_ID = 50;
SELECT COUNTRY_ID FROM LOCATIONS WHERE LOCATION_ID=1500;

SELECT COUNTRY_NAME FROM COUNTRIES WHERE COUNTRY_ID=
    (SELECT COUNTRY_ID FROM LOCATIONS WHERE LOCATION_ID=
        (SELECT LOCATION_ID FROM DEPARTMENTS WHERE DEPARTMENT_ID = 
            (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 
                (SELECT MANAGER_ID FROM EMPLOYEES WHERE EMPLOYEE_ID = 199))));
                
--사원들 중에서 급여가 제일 많은사원과 같은 부서에 근무하는 사원들의 모든 정보를 출력
SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE SALARY = 24000;
SELECT MAX(SALARY) FROM EMPLOYEES;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 
    (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE SALARY = 
    (SELECT MAX(SALARY) FROM EMPLOYEES));
--사원들 중에서 급여가 제일 많이 받는 사원, 급여가 제일 적게받는 사원과 같은부서에 근무하는 사원들의 모든정보
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 
    (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE SALARY = 
    (SELECT MIN(SALARY) FROM EMPLOYEES));

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 50 || 90;

--평균급여보다 많이받는 사원들의 부서정보

SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY>
    (SELECT AVG(SALARY)
    FROM EMPLOYEES);

--SEATTLE이라는 도시에 근무하는 사원

SELECT *
FROM LOCATIONS;

SELECT LOCATION_ID FROM LOCATIONS WHERE CITY='Seattle';
SELECT DEPARTMENT_ID FROM DEPARTMENTS;

SELECT * FROM DEPARTMENTS;

SELECT E.LAST_NAME, E.SALARY, D.DEPARTMENT_NAME
FROM EMPLOYEES E
    INNER JOIN
    DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.EMPLOYEE_ID=100;

--사원번호가 192번 사원의 이름, 월급, 부서명, 도시명
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS;

--SELECT E.LAST_NAME, E.SALARY, D.DEPARTMENT_NAME,L.CITY
SELECT *
FROM EMPLOYEES E
INNER JOIN
DEPARTMENTS D
--ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
USING(DEPARTMENT_ID)
INNER JOIN
LOCATIONS L 
ON D.LOCATION_ID = L.LOCATION_ID
WHERE E.EMPLOYEE_ID=192;

SELECT *
FROM JOBS;

SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
    INNER JOIN
    DEPARTMENTS D
    USING(DEPARTMENT_ID)
WHERE E.EMPLOYEE_ID=100;    

--SELF JOIN 사번이 192번인 사원의 이름,월급,매니저이름,매니저월급

--1.JOIN------------------------------


SELECT E.LAST_NAME, E.SALARY, M.LAST_NAME, M.SALARY
FROM EMPLOYEES E
    INNER JOIN
    EMPLOYEES M
    ON(E.MANAGER_ID=M.EMPLOYEE_ID)
WHERE E.EMPLOYEE_ID=192;

SELECT *
FROM EMPLOYEES;

--2.SUBQUERY---------------------------
SELECT
    LAST_NAME,
    SALARY,
    (
        SELECT LAST_NAME
        FROM EMPLOYEES 
        WHERE EMPLOYEE_ID=
            (
                SELECT MANAGER_ID
                FROM EMPLOYEES
                WHERE EMPLOYEE_ID=192
            )
    )AS MANAGER_NAME,
    (
        SELECT SALARY
        FROM EMPLOYEES
        WHERE EMPLOYEE_ID=
        (
         SELECT MANAGER_ID
         FROM EMPLOYEES
         WHERE EMPLOYEE_ID=192
        )
    )AS MANAGER_SALARY
FROM EMPLOYEES
WHERE EMPLOYEE_ID=192;
---------------------------------------------------
----------178 NULL--
SELECT E.EMPLOYEE_ID, E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM EMPLOYEES E
     LEFT JOIN
     DEPARTMENTS D
     ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
ORDER BY E.EMPLOYEE_ID DESC;
-----------------------------------------------------
SELECT E.EMPLOYEE_ID, E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM DEPARTMENTS D
     FULL JOIN
     EMPLOYEES E
     ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
ORDER BY E.EMPLOYEE_ID DESC;
